PlagDetec/PlagDetec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^assignments/', include('assignments.urls')),
    url(r'^', include('assignments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PlagDetec/assignments/urls.py
from django.conf.urls import url
from . import views


app_name = 'assignments'

urlpatterns = [
    # /assignments/
    url(r'^$', views.index, name='index'),

    # /assignments/homework/
    url(r'^homework/$', views.hw_index, name='hw_index'),

    # /assignments/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /assignments/login_user/
    url(r'^login_user/$', views.user_login, name='login_user'),

    # /assignments/logout_user/
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    # /assignments/7/
    url(r'^(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    # /assignments/hw/7
    url(r'^hw/(?P<hw_id>[0-9]+)/$', views.hw_detail, name='hw_detail'),

    # /assignments/task/add/
    url(r'task/add/$', views.TaskCreate.as_view(), name='task-add'),

    # /assignments/task/7/
    url(r'task/(?P<pk>[0-9]+)/$', views.TaskUpdate.as_view(), name='task-update'),

    # /assignments/task/7/delete/
    url(r'task/(?P<pk>[0-9]+)/delete/$', views.TaskDelete.as_view(), name='task-delete'),

    # /assignments/7/hw/add/
    url(r'(?P<task_id>[0-9]+)/hw/add/$', views.create_hw, name='hw-add'),

    # /assignments/7/hw/9
    # url(r'(?P<task_id>[0-9]+)/hw/(?P<hw_id>[0-9]+)/$', views.update_hw, name='hw-update'),

    # /assignments/7/hw/9/delete/
    url(r'(?P<task_id>[0-9]+)/hw/(?P<hw_id>[0-9]+)/delete/$', views.delete_hw, name='hw-delete'),

    # /assignments/7/plagdetec/
    url(r'(?P<task_id>[0-9]+)/plagdetec/$', views.plagdetec, name='plagdetec'),

    # /assignments/sim_detail/3/4/
    url(r'^sim_detail/(?P<hw_id1>[0-9]+)/(?P<hw_id2>[0-9]+)/$', views.sim_detail, name='sim_detail'),
]


PlagDetec/assignments/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User


class Task(models.Model):
    course = models.CharField(max_length=20)
    task_title = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)

    def get_absolute_url(self):
        return reverse('assignments:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.course + ' - ' + self.task_title


class Hw(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='hw')
    hw_title = models.CharField(max_length=100)
    hw_content = models.TextField(max_length=10000)
    hw_object = models.FileField(null=True, blank=True)
    writer = models.ForeignKey(User)

    def __str__(self):
        return self.hw_title

PlagDetec/assignments/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Hw


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    # information about this class
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class HwForm(forms.ModelForm):

    class Meta:
        model = Hw
        fields = ['hw_title', 'hw_content', 'hw_object']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

PlagDetec/assignments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import View
from .models import Task, Hw
from .forms import UserForm, HwForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.contrib import messages


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        all_tasks = Task.objects.all()

        query = request.GET.get("q")
        if query:
            all_tasks = Task.objects.filter(
                Q(task_title__icontains=query) |
                Q(course__icontains=query)
            ).distinct()
            return render(request, 'assignments/index.html', {'all_tasks': all_tasks})

        return render(request, 'assignments/index.html', {'all_tasks': all_tasks})


def hw_index(request):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        hws = Hw.objects.all()
        return render(request, 'assignments/hw_index.html', {'hws': hws})


def hw_detail(request, hw_id):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        hw = get_object_or_404(Hw, pk=hw_id)
        task = get_object_or_404(Task, pk=hw.task.id)
        hws = task.hw.all()
        if hw.writer == request.user or request.user.username == 'admin':
            return render(request, 'assignments/hw_detail.html', {'hw': hw})
        else:
            return render(request, 'assignments/detail.html', {'task': task,
                                                               'hws': hws,
                                                               })


def detail(request, task_id):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        task = get_object_or_404(Task, pk=task_id)
        hws = task.hw.all()
        return render(request, 'assignments/detail.html', {'task': task,
                                                           'hws': hws,
                                                           })


def plagdetec(request, task_id):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        task = get_object_or_404(Task, pk=task_id)
        hws = task.hw.all()
        i_range = range(hws.count())
        j_range = range(hws.count())
        return render(request, 'assignments/plagdetec.html', {'task': task,
                                                               'hws': hws,
                                                               'i_range': i_range,
                                                               'j_range': j_range, })


def sim_detail(request, hw_id1, hw_id2):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        hw1 = get_object_or_404(Hw, pk=hw_id1)
        hw2 = get_object_or_404(Hw, pk=hw_id2)
        return render(request, 'assignments/sim_detail.html', {'hw1': hw1, 'hw2': hw2})


# 出现NoReverseMatch错误是因为url里匹配的变量名是task_id, 不是pk
# @permission_required('tasks.add_task')
class TaskCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('tasks.add_task',)
    model = Task
    fields = ['course', 'task_title', 'description']

    def handle_no_permission(self):
        messages.error(self.request, '你没有此行为的权限！')
        return redirect('/assignments/')


class TaskUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('tasks.change_task',)
    model = Task
    fields = ['course', 'task_title', 'description']

    def handle_no_permission(self):
        messages.error(self.request, '你没有此行为的权限！')
        return redirect('/assignments/')


class TaskDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('tasks.delete_task',)
    model = Task
    success_url = reverse_lazy('assignments:index')

    def handle_no_permission(self):
        messages.error(self.request, '你没有此行为的权限！')
        return redirect('/assignments/')


def create_hw(request, task_id):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        task = get_object_or_404(Task, pk=task_id)
        form = HwForm(None or request.POST, request.FILES)
        if form.is_valid():
            task_hws = task.hw.all()
            for h in task_hws:
                if h.hw_title == form.cleaned_data.get("hw_title"):
                    context = {
                        'task': task,
                        'form': form,
                        'error_message': '你已经提交了该作业',
                    }
                    return render(request, 'assignments/hw_form.html', context)
            hw = form.save(commit=False)
            hw.task = task
            hw.writer = request.user
            hw.save()
            return render(request, 'assignments/detail.html', {'task': task})
        context = {
            'task': task,
            'form': form,
        }
        return render(request, 'assignments/hw_form.html', context)


# def update_hw(request, task_id, hw_id):
#     task = get_object_or_404(Task, pk=task_id)
#     hwk = Hw.objects.get(pk=hw_id)
#
#     # form = HwForm(request.POST or None, initial={'task': task, 'hw_title': hwk.hw_title, 'hw_content': hwk.hw_content})
#     form = HwForm(request.POST or None, initial={'task': task})
#     if form.is_valid():
#         task_hws = task.hw.all()
#         for h in task_hws:
#             if h.hw_title == form.cleaned_data.get("hw_title"):
#                 context = {
#                     'task': task,
#                     'form': form,
#                     'error_message': 'You already added that song',
#                 }
#                 return render(request, 'assignments/hw_form.html', context)
#         hw = form.save(commit=False)
#         hw.task = task
#         hw.save()
#         return render(request, 'assignments/detail.html', {'task': task})
#     context = {
#         'task': task,
#         'form': form,
#     }
#     return render(request, 'assignments/hw_form.html', context)


def delete_hw(request, task_id, hw_id):
    if not request.user.is_authenticated():
        return render(request, 'assignments/login.html')
    else:
        task = get_object_or_404(Task, pk=task_id)
        hws = task.hw.all()
        hw = Hw.objects.get(pk=hw_id)
        if hw.writer == request.user or request.user.username == 'admin':
            hw.delete()
            return render(request, 'assignments/detail.html', {'task': task})
        else:
            return render(request, 'assignments/detail.html', {'task': task,
                                                               'hws': hws,
                                                               })


class UserFormView(View):
    form_class = UserForm
    template_name = 'assignments/registration_form.html'

    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # submit some user data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return User object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('assignments:index')

        return render(request, self.template_name, {'form': form})


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_tasks = Task.objects.all()
                return render(request, 'assignments/index.html', {'all_tasks': all_tasks})
                # return redirect('assignments:index', context={'all_tasks': all_tasks})
            else:
                return render(request, 'assignments/login.html', {'error_message': 'Your account has been disabled'})

        else:
            return render(request, 'assignments/login.html', {'error_message': 'Invalid login'})
    return render(request, 'assignments/login.html')


@login_required
def logout_user(request):
    logout(request)
    # form = UserForm(request.POST or None)
    # context = {
    #     "form": form,
    # }
    return render(request, 'assignments/login.html')

PlagDetec/assignments/templates/assignments/base.html
{% load tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'assignments/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'assignments:index' %}">易业</a>
        </div>


        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block tasks_active %}{% endblock %}">
                    <a href="{% url 'assignments:index' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        任务
                    </a>
                </li>
                <li class="{% block hws_active %}{% endblock %}">
                    <a href="{% url 'assignments:hw_index' %}">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                        文件
                    </a>
                </li>
            </ul>


            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'assignments:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>


            <ul class="nav navbar-nav navbar-right">
                <span class="user">
                    {% if request.user.is_authenticated %}
                        <li class="">

                        </li>
                    {% endif %}
                </span>
                <li class="">
                    <a href="{% url 'assignments:task-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        添加新任务
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'assignments:logout_user' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        退出
                    </a>
                </li>
            </ul>


        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

PlagDetec/assignments/templates/assignments/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}易业{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'assignments/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'assignments:index' %}">易业</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'assignments:register' %}">注册</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'assignments:login_user' %}">登录</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

PlagDetec/assignments/templates/assignments/detail.html
{% extends 'assignments/base.html' %}
{% block hws_active %}active{% endblock %}

{% load tag %}

{% block title %}{{ task.task_title }}{% endblock %}
{% block body %}
<div class="container-fluid task-container">

    <div class="row">

        <!-- Left Task Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'assignments:detail' task.id %}">
                        <img src="/media/hwicon.png" class="img-responsive">
                    </a>
                    <h2>{{ task.course }}</h2>
                    <h4>{{ task.task_title }}</h4>
                    <small>{{ task.description }}</small>
                </div>
                <div class="panel-footer">
                    <a class="btn btn-warning btn-sm" href="{% url 'assignments:task-update' task.id %}" role="button"><span class="glyphicon glyphicon-refresh" aria-hidden="true"> 修改</span></a>&nbsp
                    <form action="{% url 'assignments:task-delete' task.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="task_id" value="{{ task.id }}" />
                        <button type="submit" class="btn btn-danger btn-sm">
                            <span class="glyphicon glyphicon-trash"> 删除</span>
                        </button>&nbsp
                    </form>
                    <a class="btn btn-primary btn-sm" href="{% url 'assignments:plagdetec' task.id %}" role="button"><span class="glyphicon glyphicon-search" aria-hidden="true"> 查重</span></a>
                </div>

            </div>
        </div>

        <!-- Right Homework Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'assignments:detail' task.id %}">该任务下的所有文件</a></li>
                <li role="presentation"><a href="{% url 'assignments:hw-add' task.id %}">提交新的作业文件</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>该任务下的所有文件</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>文件名</th>
                            <th>作者</th>
                            <th>句数</th>
                            <th>动作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for hw in task.hw.all %}
                            <tr>
                                <td>
                                    {{ hw.hw_title }}
                                </td>
                                <td>
                                    {{ hw.writer }}
                                </td>
                                <td>
                                    {{ hw.hw_content|get_sentencecount }}
                                </td>
                                <td>
                                    <a class="btn btn-success btn-xs" href="{% url 'assignments:hw_detail' hw.id %}" role="button"><span class="glyphicon glyphicon-search" aria-hidden="true"> 查看详情</span></a>

                                    <form action="{% url 'assignments:hw-delete' task.id hw.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="hw_id" value="{{ hw.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; 删除
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

PlagDetec/assignments/templates/assignments/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10" >
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2">{{ field.label_tag }}</label>

        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

PlagDetec/assignments/templates/assignments/hw_detail.html
{% extends 'assignments/base.html' %}

{% block hws_active %}active{% endblock %}

{% load tag %}

{% block body %}
<div class="container-fluid task-container">
    <div class="row">
        <div class="col col-sm-9 align-items-center">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ hw.hw_title }}</h3>
                </div>
                <div class="panel-body">
                    {{ hw.hw_content|linebreaks }}
                </div>
            </div>
        </div>

        <div class="col col-sm-3 align-items-center">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">统计信息</h3>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <th>作者</th><th>字符数</th><th>句数</th>
                        <tr><td>{{ hw.writer }}</td><td>{{ hw.hw_content|get_charcount }}</td><td>{{ hw.hw_content|get_sentencecount }}</td></tr>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

PlagDetec/assignments/templates/assignments/hw_index.html
{% extends 'assignments/base.html' %}

{% block hws_active %}active{% endblock %}
{% block title %}作业文件{% endblock %}

{% block body %}

<div class="container-fluid task-container">
<div class="row">
    <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>所有文件</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>文件名</th>
                            <th>作者</th>
                            <th>所属任务</th>
                            <th>动作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for hw in hws %}
                            <tr>
                                <td>
                                    {{ hw.hw_title }}
                                </td>
                                <td>
                                    {{ hw.writer }}
                                </td>
                                <td>
                                    {{ hw.task }}
                                </td>
                                <td>
                                    <a class="btn btn-success btn-xs" href="{% url 'assignments:hw_detail' hw.id %}" role="button"><span class="glyphicon glyphicon-search" aria-hidden="true">查看文件详情</span></a>
                                    <a class="btn btn-primary btn-xs" href="{% url 'assignments:detail' hw.task.id %}" role="button"><span class="glyphicon glyphicon-search" aria-hidden="true">查看所属任务详情</span></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

PlagDetec/assignments/templates/assignments/index.html
{% extends 'assignments/base.html' %}

{% block tasks_active %}active{% endblock %}
{% block title %}作业任务{% endblock %}
{% block body %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% else %}

    <div class="container-fluid task-container">

    <div class="row">
        <div class="col-sm-12">
            <h2>作业任务如下:</h2>
        </div>

        {% if all_tasks %}
            {% for task in all_tasks %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'assignments:detail' task.id %}">
                            <img src="../media/hwicon.png" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h3>{{ task.course }}</h3>
                            <h4>{{ task.task_title }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'assignments:detail' task.id %}" class="btn btn-primary btn-sm" role="button">查看详情</a>

                            <form action="{% url 'assignments:task-delete' task.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="task_id" value="{{ task.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'assignments:task-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;添加新任务
                    </button>
                </a>
            </div>
        {% endif %}

    </div>

    </div>

{% endif %}

{% endblock %}

PlagDetec/assignments/templates/assignments/intro.html
{% extends 'assignments/base.html' %}

{% block body %}
<!-- header -->
<header class="header ">
  <div class="overlay"></div>
   <div class="container">
   	  <div class="description ">
  	<h1>
  		Hello ,Welcome To My official Website
  		<p>
  		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  		<button class="btn btn-outline-secondary btn-lg">See more</button>
  	</h1>
  </div>
   </div>

</header>


{% endblock %}

PlagDetec/assignments/templates/assignments/login.html
{% extends 'assignments/base_visitor.html' %}
{% block title %}登录{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>登录</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'assignments:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    还没有账号？<a href="{% url 'assignments:register' %}">点击此处</a> 注册.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}
